### PR TITLE
To Do list: list structure 🚶 

### PR DESCRIPTION
**Pull request by ritikarawat220**
### Basic Application Layout

**➡️    Setup webpack project.
➡️   Add basic layout and list items.
➡️   Add clear button and checkboxes.**

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @ritikarawat220 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional readme
Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme,


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
Hi @ritikarawat220, Kindly use the updated version of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, this was stated in the invalidation message above, all sections from the readme should be in your readme with the content tailored to your project, only the FAQ section is optional

**Comment by ritikarawat220** [comment]
> Hi @ritikarawat220, Kindly use the updated version of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, this was stated in the invalidation message above, all sections from the readme should be in your readme with the content tailored to your project, only the FAQ section is optional

**Review by prolajumokeoni — APPROVED** [review]
Hi @ritikarawat220 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 - Array of simple todo tasks ✅ 
 - Webpack is setup correctly 🚀  



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ritikarawat220** [comment]
Thanks for the approval.. 😄👍🏻

**Pull request merged**
